#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy exfat-fuse | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "exfat-fuse ->  [${V0}]"
V1=$(apt-cache policy exfat-utils | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "exfat-utils ->  [${V1}]"
