#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'ppa-purge' | grep -q "\[installed\]")
then
   echo "[ppa-purge] -> [installed!]";
else
   echo "[ppa-purge] -> [NOT installed!]";
   missing=1;
fi
