#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > gparted
#		 > apt

printf "gparted > %s\n" "$(apt-cache policy gparted | grep Candidate | cut -d: -f2 | tr -d /" /")"
