#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: checkinstall
#		 > Template: apt

printf "checkinstall > %s\n" "$(apt-cache policy checkinstall | grep Installed | cut -d: -f2 | tr -d /" /")"
