#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > checkinstall
#		 > apt

printf "checkinstall > %s\n" "$(apt-cache policy checkinstall | grep Installed | cut -d: -f2 | tr -d /" /")"
