#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: checkinstall
#		 > Template: apt

printf "checkinstall > %s\n" "$(apt-cache policy checkinstall | grep Candidate | cut -d: -f2 | tr -d /" /")"
