#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: ansifilter
#		 > Template: apt

printf "ansifilter > %s\n" "$(apt-cache policy ansifilter | grep Installed | cut -d: -f2 | tr -d /" /")"
