#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > ansifilter
#		 > apt

printf "ansifilter > %s\n" "$(apt-cache policy ansifilter | grep Candidate | cut -d: -f2 | tr -d /" /")"
