#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: vlc
#		 > Template: apt

printf "vlc > %s\n" "$(apt-cache policy vlc | grep Installed | cut -d: -f2 | tr -d /" /")"
