#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: vlc
#		 > Template: apt

printf "vlc > %s\n" "$(apt-cache policy vlc | grep Candidate | cut -d: -f2 | tr -d /" /")"
