#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: neovim
#		 > Template: bin

# Variables
# <<<PRE STAGE>>>

mkdir -p "${HOME}/.config/nvim"

INSTALL_DST="${INSTALL_DST:-/usr/local/bin}"
BASHCOMP_P="${BASHCOMP_P:-${HOME}/.config/bash/bash_completion}"
ZSHCOMP="${ZSHCOMP:-${HOME}/.config/zsh/completions}"
TEMPDIR="$(mktemp -d -t XXXXXXXXXX)"
FMT='\e[0;34m%-6s\e[m\n'
# Commands
DLTMP=$(mktemp -d -t jumpstart-XXXXXXXXXX) \
&& cd "${DLTMP}" \
&& printf "\e[0;34m%-6s\e[m\n" "Downloading to $(realpath .)" \
&& URL=$(curl --silent 'https://api.github.com/repos/neovim/neovim/releases/latest' | jq '..|.browser_download_url? | select( . != null )' | tr -d '"' | grep --ignore-case '\.appimage' | grep --ignore-case --invert-match 'zsync' | grep --ignore-case --invert-match 'sha256sum') \
&& curl -jLO "${URL}" \
&& DLFILE=$(ls . | head -n1) \
&& SRCPATH=$( find . -type f | grep --ignore-case 'nvim' ) \
&& sudo chmod +x "${SRCPATH}" \
&& sudo mv "${SRCPATH}" "${INSTALL_DST}/nvim"

# <<<POST STAGE>>>

printf "\e[0;34m%-6s\e[m\n" "Download_icon" \
&& sudo wget "https://raw.githubusercontent.com/neovim/neovim.github.io/master/logos/neovim-mark.svg" --continue --output-document="/usr/share/icons/neovim.svg"
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
