#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: xclip
#		 > Template: apt

printf "xclip > %s\n" "$(apt-cache policy xclip | grep Installed | cut -d: -f2 | tr -d /" /")"
