#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: sqlite
#		 > Template: apt

sudo apt-get remove -y sqlite3 sqlite3-tools sqlitebrowser
