#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > graphviz
#		 > apt

printf "graphviz > %s\n" "$(apt-cache policy graphviz | grep Installed | cut -d: -f2 | tr -d /" /")"
