#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: graphviz
#		 > Template: apt

printf "graphviz > %s\n" "$(apt-cache policy graphviz | grep Candidate | cut -d: -f2 | tr -d /" /")"
