#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > graphviz
#		 > apt

printf "graphviz > %s\n" "$(apt-cache policy graphviz | grep Candidate | cut -d: -f2 | tr -d /" /")"
