#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'p7zip-full' | grep -q "\[installed\]")
then
   echo "[p7zip-full] -> [installed!]";
else
   echo "[p7zip-full] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'p7zip-rar' | grep -q "\[installed\]")
then
   echo "[p7zip-rar] -> [installed!]";
else
   echo "[p7zip-rar] -> [NOT installed!]";
   missing=1;
fi
