#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy p7zip-full | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "p7zip-full ->  [${V0}]"
V1=$(apt-cache policy p7zip-rar | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "p7zip-rar ->  [${V1}]"
