#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'vim' | grep -q "\[installed\]")
then
   echo "[vim] -> [installed!]";
else
   echo "[vim] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'vim-gtk' | grep -q "\[installed\]")
then
   echo "[vim-gtk] -> [installed!]";
else
   echo "[vim-gtk] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'vim-tiny' | grep -q "\[installed\]")
then
   echo "[vim-tiny] -> [installed!]";
else
   echo "[vim-tiny] -> [NOT installed!]";
   missing=1;
fi
