#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: screenkey
#		 > Template: apt

printf "screenkey > %s\n" "$(apt-cache policy screenkey | grep Installed | cut -d: -f2 | tr -d /" /")"
