#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > screenkey
#		 > apt

printf "screenkey > %s\n" "$(apt-cache policy screenkey | grep Installed | cut -d: -f2 | tr -d /" /")"
