#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: screenkey
#		 > Template: apt

printf "screenkey > %s\n" "$(apt-cache policy screenkey | grep Installed | cut -d: -f2 | tr -d /" /")"
