#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: hyperfine
#		 > Template: apt

printf "hyperfine > %s\n" "$(apt-cache policy hyperfine | grep Installed | cut -d: -f2 | tr -d /" /")"
