#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > hyperfine
#		 > apt

printf "hyperfine > %s\n" "$(apt-cache policy hyperfine | grep Candidate | cut -d: -f2 | tr -d /" /")"
