#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: Blender
#		 > Template: flatpak

flatpak install -y flathub org.blender.Blender
