#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > Blender
#		 > flatpak

printf "org.blender.Blender > %s\n" "$(flatpak info org.blender.Blender | grep Version | cut -d: -f2 | tr -d /" /")"
