#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Blender
#		 > Template: flatpak

printf "org.blender.Blender > %s\n" "$(flatpak search org.blender.Blender | head -n1 | cut -f4 | tr -d /" /")"
