#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > Blender
#		 > flatpak

printf "org.blender.Blender > %s\n" "$(flatpak search org.blender.Blender | head -n1 | cut -f4 | tr -d /" /")"
