#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > pavucontrol
#		 > apt

printf "pavucontrol > %s\n" "$(apt-cache policy pavucontrol | grep Installed | cut -d: -f2 | tr -d /" /")"
