#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: pavucontrol
#		 > Template: apt

printf "pavucontrol > %s\n" "$(apt-cache policy pavucontrol | grep Installed | cut -d: -f2 | tr -d /" /")"
