#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > pavucontrol
#		 > apt

printf "pavucontrol > %s\n" "$(apt-cache policy pavucontrol | grep Candidate | cut -d: -f2 | tr -d /" /")"
