#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PKGS: gnome-themes-standard gtk2-engines-murrine libglib2.0-dev libxml2-utils materia-gtk-theme
sudo apt-get install -y \
	gnome-themes-standard \
	gtk2-engines-murrine \
	libglib2.0-dev \
	libxml2-utils \
	materia-gtk-theme
