#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo apt-get remove -y gnome-themes-standard
sudo apt-get remove -y gtk2-engines-murrine
sudo apt-get remove -y libglib2.0-dev
sudo apt-get remove -y libxml2-utils
sudo apt-get remove -y materia-gtk-theme
