#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'gnome-themes-standard' | grep -q "\[installed\]")
then
   echo "[gnome-themes-standard] -> [installed!]";
else
   echo "[gnome-themes-standard] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'gtk2-engines-murrine' | grep -q "\[installed\]")
then
   echo "[gtk2-engines-murrine] -> [installed!]";
else
   echo "[gtk2-engines-murrine] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'libglib2.0-dev' | grep -q "\[installed\]")
then
   echo "[libglib2.0-dev] -> [installed!]";
else
   echo "[libglib2.0-dev] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'libxml2-utils' | grep -q "\[installed\]")
then
   echo "[libxml2-utils] -> [installed!]";
else
   echo "[libxml2-utils] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'materia-gtk-theme' | grep -q "\[installed\]")
then
   echo "[materia-gtk-theme] -> [installed!]";
else
   echo "[materia-gtk-theme] -> [NOT installed!]";
   missing=1;
fi
