#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy gnome-themes-standard | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "gnome-themes-standard ->  [${V0}]"
V1=$(apt-cache policy gtk2-engines-murrine | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "gtk2-engines-murrine ->  [${V1}]"
V2=$(apt-cache policy libglib2.0-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libglib2.0-dev ->  [${V2}]"
V3=$(apt-cache policy libxml2-utils | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libxml2-utils ->  [${V3}]"
V4=$(apt-cache policy materia-gtk-theme | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "materia-gtk-theme ->  [${V4}]"
