#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy curl | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "curl ->  [${V0}]"
V1=$(apt-cache policy iputils-ping | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "iputils-ping ->  [${V1}]"
V2=$(apt-cache policy wget | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "wget ->  [${V2}]"
