# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
# Update the 'rev's:
#   pre-commit autoupdate --freeze
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^packages/
      - id: trailing-whitespace
      - id: mixed-line-ending
  #  - repo: https://github.com/python-poetry/poetry
  #    rev: '3f741f77a2822b6fe0cdf2f27cce2c701e011fc2'  # frozen: 1.2.0rc1
  #    hooks:
  #      - id: poetry-check
  - repo: https://github.com/trailofbits/pip-audit
    rev: d94110af0c8a31edacd8d9e49cd02c18f9632a79 # frozen: v2.4.15
    hooks:
      - id: pip-audit
        args:
          [
            "--ignore-vuln",
            "GHSA-8849-5h85-98qw",
            "--ignore-vuln",
            "GHSA-m6vm-8g8v-xfjh",
          ]
  - repo: https://github.com/PyCQA/bandit
    rev: "1ed79063e3672a1c6d91ee27cb648e07a7465344" # frozen: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies:
          - toml
  - repo: https://github.com/pycqa/isort
    rev: dbf82f2dd09ae41d9355bcd7ab69187a19e6bf2f # frozen: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: b0d1fba7ac3be53c71fb0d3211d911e629f8aecb # frozen: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1238e1d8f03e96a7ed9ad44937ea4348eb6b11b8 # frozen: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=20.8b1]
  - repo: https://github.com/PyCQA/flake8
    rev: c838a5e98878f17889cfce311e1406d252f87ec5 # frozen: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
          - flake8-typing-imports==1.14.0
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: 01cee377ba3a5264c7fbe7b6beae7b575f764dc3 # frozen: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "cafd5506f18eea191804850dacc0a4264772d59d" # frozen: v3.0.0-alpha.4
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "dc6912646c561f16af711006e7615d52e9bf0968" # frozen: v1.0.0
    hooks:
      - id: mypy
        additional_dependencies: [marshmallow_dataclass]
