# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
# Update the 'rev's:
#   pre-commit autoupdate --freeze
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^packages/
      - id: trailing-whitespace
      - id: mixed-line-ending
  #  - repo: https://github.com/python-poetry/poetry
  #    rev: '3f741f77a2822b6fe0cdf2f27cce2c701e011fc2'  # frozen: 1.2.0rc1
  #    hooks:
  #      - id: poetry-check
  - repo: https://github.com/trailofbits/pip-audit
    rev: 0fc0329cefbeeaa7aaafdb564ee460043ddd0ff0 # frozen: v2.5.5
    hooks:
      - id: pip-audit
        args:
          [
            "--ignore-vuln",
            "GHSA-8849-5h85-98qw",
            "--ignore-vuln",
            "GHSA-m6vm-8g8v-xfjh",
          ]
  - repo: https://github.com/PyCQA/bandit
    rev: "ca4faf2f82a7c68a088100f8ba2b8e56f9bdcfe3" # frozen: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies:
          - bandit[toml]
  - repo: https://github.com/pycqa/isort
    rev: dbf82f2dd09ae41d9355bcd7ab69187a19e6bf2f # frozen: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: bf7a16254ec96b084a6caf3d435ec18f0f245cc7 # frozen: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1238e1d8f03e96a7ed9ad44937ea4348eb6b11b8 # frozen: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black>=20.8b1]
  - repo: https://github.com/PyCQA/flake8
    rev: c838a5e98878f17889cfce311e1406d252f87ec5 # frozen: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
          - flake8-typing-imports==1.14.0
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: 1395c21a149988e686aef88be48d52ba0d5752f3 # frozen: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "6fd1ced85fc139abd7f5ab4f3d78dab37592cd5e" # frozen: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "bd424e49d4f0181d4c8b8909a8cd5ce9eb058044" # frozen: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [marshmallow_dataclass]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 3f77b826548d8dc2d26675f077361c92773b50a7 # frozen: v0.9.0
    hooks:
      - id: shellcheck
        exclude: |
          (?x)^(
            jumpstart/.*|
            packages/.*\.pre/.*|
            packages/.*\.post/.*
          )$

# https://pre-commit.com/#regular-expressions
