# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
# Update the 'rev's:
#   pre-commit autoupdate --freeze
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: f6f816c65d285f8a4a15e0e9965b3dd66ecddd79  # frozen: v0.931
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports ]
        additional_dependencies:
          - numpy
          - marshmallow_dataclass
  - repo: https://github.com/pycqa/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files" ]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: fc0be6eb1e2a96091e6f64009ee5e9081bf8b6c6  # frozen: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 7ae9389351f4090e3993de28015a05a18ca6b8a7  # frozen: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black>=20.8b1 ]
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: dcd740bc0ebaf2b3d43e59a0060d157c97de13f3  # frozen: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
          - flake8-typing-imports==1.10.1
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: e695ecd365119ab4e5463f6e49bea5f4b7ca786b  # frozen: v2.31.0
    hooks:
      - id: pyupgrade
        args: [ --py36-plus ]
