# vim: ft=dosini
[tool.isort]
profile = "black"
# multi_line_output = 3
# include_trailing_comma = true
# force_grid_wrap = 0
# use_parentheses = true
# ensure_newline_before_comments = false
# line_length = 10

[tool.black]
line-length = 121


[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#config-precedence
python_version = "3.8"
warn_unused_configs = true
# CLEAN UP EVENTUALLY
warn_return_any = false
disallow_untyped_defs = false
# disable_error_code = ['import', 'no-untyped-def', 'attr-defined', 'no-redef', 'assignment', 'return-value', 'operator', 'type-var', 'call-arg']
