#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: VSCodium
#		 > Template: deb

# Variables

# Commands
DLTMP=$(mktemp -d -t jumpstart-XXXXXXXXXX) \
&& cd "${DLTMP}" \
&& printf "\e[0;34m%-6s\e[m\n" "Downloading to $(realpath .)" \
&& URL=$(curl --silent 'https://api.github.com/repos/vscodium/vscodium/releases/latest' | jq '..|.browser_download_url? | select( . != null )' | tr -d '"' | grep --ignore-case 'amd64' | grep --ignore-case 'deb"') \
&& curl -jLO "${URL}" \
&& DLFILE=$(ls . | head -n1) \
&& sudo apt install -y "$(realpath ${DLFILE})"
