#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PKGS: texlive-fonts-extra texlive-full texlive-latex-extra texlive-xetex texstudio
sudo apt-get install -y \
	texlive-fonts-extra \
	texlive-full \
	texlive-latex-extra \
	texlive-xetex \
	texstudio
