#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo apt-get remove -y texlive-fonts-extra
sudo apt-get remove -y texlive-full
sudo apt-get remove -y texlive-latex-extra
sudo apt-get remove -y texlive-xetex
sudo apt-get remove -y texstudio
