#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'texlive-fonts-extra' | grep -q "\[installed\]")
then
   echo "[texlive-fonts-extra] -> [installed!]";
else
   echo "[texlive-fonts-extra] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'texlive-full' | grep -q "\[installed\]")
then
   echo "[texlive-full] -> [installed!]";
else
   echo "[texlive-full] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'texlive-latex-extra' | grep -q "\[installed\]")
then
   echo "[texlive-latex-extra] -> [installed!]";
else
   echo "[texlive-latex-extra] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'texlive-xetex' | grep -q "\[installed\]")
then
   echo "[texlive-xetex] -> [installed!]";
else
   echo "[texlive-xetex] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'texstudio' | grep -q "\[installed\]")
then
   echo "[texstudio] -> [installed!]";
else
   echo "[texstudio] -> [NOT installed!]";
   missing=1;
fi
