#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: netcat
#		 > Template: apt

printf "nc > %s\n" "$(apt-cache policy nc | grep Installed | cut -d: -f2 | tr -d /" /")"
