#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: netcat
#		 > Template: apt

printf "nc > %s\n" "$(apt-cache policy nc | grep Candidate | cut -d: -f2 | tr -d /" /")"
