#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: virtualbox
#		 > Template: apt

sudo apt-get install -y virtualbox virtualbox-dkms virtualbox-ext-pack virtualbox-guest-dkms
