#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

sudo apt-get install -y virtualbox virtualbox-dkms virtualbox-ext-pack virtualbox-guest-dkms

# <<<POST-AUTOGENERATED FILE - DO NOT MODIFY>>>
