#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: virtualbox
#		 > Template: apt

sudo apt-get remove -y virtualbox virtualbox-dkms virtualbox-ext-pack virtualbox-guest-dkms
