#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: bashtop-monitor/bashtop
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:bashtop-monitor/bashtop
sudo apt-get update -y
# >>>> PKGS: bashtop
sudo apt-get install -y \
	bashtop
