#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > gromit-mpx
#		 > flatpak

printf "net.christianbeier.Gromit-MPX > %s\n" "$(flatpak info net.christianbeier.Gromit-MPX | grep Version | cut -d: -f2 | tr -d /" /")"
