#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: gromit-mpx
#		 > Template: flatpak

printf "net.christianbeier.Gromit-MPX > %s\n" "$(flatpak info net.christianbeier.Gromit-MPX | grep Version | cut -d: -f2 | tr -d /" /")"
