#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: gromit-mpx
#		 > Template: flatpak

flatpak uninstall net.christianbeier.Gromit-MPX  --delete-data
