#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > gromit-mpx
#		 > flatpak

printf "net.christianbeier.Gromit-MPX > %s\n" "$(flatpak search net.christianbeier.Gromit-MPX | head -n1 | cut -f4 | tr -d /" /")"
