#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: gromit-mpx
#		 > Template: flatpak

printf "net.christianbeier.Gromit-MPX > %s\n" "$(flatpak search net.christianbeier.Gromit-MPX | head -n1 | cut -f4 | tr -d /" /")"
