#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: vim
#		 > Template: apt

printf "vim > %s\n" "$(apt-cache policy vim | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "vim-gtk > %s\n" "$(apt-cache policy vim-gtk | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "vim-tiny > %s\n" "$(apt-cache policy vim-tiny | grep Installed | cut -d: -f2 | tr -d /" /")"
