#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > vim
#		 > apt

printf "vim > %s\n" "$(apt-cache policy vim | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "vim-gtk > %s\n" "$(apt-cache policy vim-gtk | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "vim-tiny > %s\n" "$(apt-cache policy vim-tiny | grep Installed | cut -d: -f2 | tr -d /" /")"
