#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "vim > %s\n" "$(apt-cache policy vim | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "vim-gtk > %s\n" "$(apt-cache policy vim-gtk | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "vim-tiny > %s\n" "$(apt-cache policy vim-tiny | grep Installed | cut -d: -f2 | tr -d /" /")"
