#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: entr
#		 > Template: apt

printf "entr > %s\n" "$(apt-cache policy entr | grep Candidate | cut -d: -f2 | tr -d /" /")"
