#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'gromit-mpx' | grep -q "\[installed\]")
then
   echo "[gromit-mpx] -> [installed!]";
else
   echo "[gromit-mpx] -> [NOT installed!]";
   missing=1;
fi
