#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: Joplin
#		 > Template: flatpak

flatpak uninstall net.cozic.joplin_desktop  --delete-data
