#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Joplin
#		 > Template: flatpak

printf "net.cozic.joplin_desktop > %s\n" "$(flatpak search net.cozic.joplin_desktop | head -n1 | cut -f4 | tr -d /" /")"
