#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: mutt
#		 > Template: apt

printf "mutt > %s\n" "$(apt-cache policy mutt | grep Installed | cut -d: -f2 | tr -d /" /")"
