#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: mutt
#		 > Template: apt

printf "mutt > %s\n" "$(apt-cache policy mutt | grep Installed | cut -d: -f2 | tr -d /" /")"
