#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: mutt
#		 > Template: apt

printf "mutt > %s\n" "$(apt-cache policy mutt | grep Candidate | cut -d: -f2 | tr -d /" /")"
