#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PKGS: filemanager-actions nautilus-extension-gnome-terminal
sudo apt-get install -y \
	filemanager-actions \
	nautilus-extension-gnome-terminal
