#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'filemanager-actions' | grep -q "\[installed\]")
then
   echo "[filemanager-actions] -> [installed!]";
else
   echo "[filemanager-actions] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'nautilus-extension-gnome-terminal' | grep -q "\[installed\]")
then
   echo "[nautilus-extension-gnome-terminal] -> [installed!]";
else
   echo "[nautilus-extension-gnome-terminal] -> [NOT installed!]";
   missing=1;
fi
