#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy filemanager-actions | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "filemanager-actions ->  [${V0}]"
V1=$(apt-cache policy nautilus-extension-gnome-terminal | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "nautilus-extension-gnome-terminal ->  [${V1}]"
