#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'dos2unix' | grep -q "\[installed\]")
then
   echo "[dos2unix] -> [installed!]";
else
   echo "[dos2unix] -> [NOT installed!]";
   missing=1;
fi
