#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: fd-find
#		 > Template: apt

printf "fd-find > %s\n" "$(apt-cache policy fd-find | grep Installed | cut -d: -f2 | tr -d /" /")"
