#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: fd-find
#		 > Template: apt

printf "fd-find > %s\n" "$(apt-cache policy fd-find | grep Candidate | cut -d: -f2 | tr -d /" /")"
