#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > fd-find
#		 > apt

printf "fd-find > %s\n" "$(apt-cache policy fd-find | grep Candidate | cut -d: -f2 | tr -d /" /")"
