#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'gstreamer1.0-libav' | grep -q "\[installed\]")
then
   echo "[gstreamer1.0-libav] -> [installed!]";
else
   echo "[gstreamer1.0-libav] -> [NOT installed!]";
   missing=1;
fi
