#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: pass
#		 > Template: apt

printf "pass > %s\n" "$(apt-cache policy pass | grep Installed | cut -d: -f2 | tr -d /" /")"
