#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: pass
#		 > Template: apt

printf "pass > %s\n" "$(apt-cache policy pass | grep Candidate | cut -d: -f2 | tr -d /" /")"
