#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > TeX Studio
#		 > flatpak

printf "org.texstudio.TeXstudio > %s\n" "$(flatpak info org.texstudio.TeXstudio | grep Version | cut -d: -f2 | tr -d /" /")"
