#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > TeX Studio
#		 > flatpak

printf "org.texstudio.TeXstudio > %s\n" "$(flatpak search org.texstudio.TeXstudio | head -n1 | cut -f4 | tr -d /" /")"
