#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: TeX Studio
#		 > Template: flatpak

printf "org.texstudio.TeXstudio > %s\n" "$(flatpak search org.texstudio.TeXstudio | head -n1 | cut -f4 | tr -d /" /")"
