#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo apt-get remove -y build-essential
sudo apt-get remove -y libffi-dev
sudo apt-get remove -y libpq-dev
sudo apt-get remove -y libssl-dev
sudo apt-get remove -y libxml2-dev
sudo apt-get remove -y libxslt1-dev
sudo apt-get remove -y pandoc
sudo apt-get remove -y pandoc-citeproc
sudo apt-get remove -y python3
sudo apt-get remove -y python3-dev
sudo apt-get remove -y python3-pip
sudo apt-get remove -y python3-venv
sudo apt-get remove -y texlive
sudo apt-get remove -y texlive-latex-extra
sudo apt-get remove -y texlive-xetex
sudo apt-get remove -y zlib1g-dev
