#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy build-essential | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "build-essential ->  [${V0}]"
V1=$(apt-cache policy libffi-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libffi-dev ->  [${V1}]"
V2=$(apt-cache policy libpq-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libpq-dev ->  [${V2}]"
V3=$(apt-cache policy libssl-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libssl-dev ->  [${V3}]"
V4=$(apt-cache policy libxml2-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libxml2-dev ->  [${V4}]"
V5=$(apt-cache policy libxslt1-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "libxslt1-dev ->  [${V5}]"
V6=$(apt-cache policy pandoc | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "pandoc ->  [${V6}]"
V7=$(apt-cache policy pandoc-citeproc | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "pandoc-citeproc ->  [${V7}]"
V8=$(apt-cache policy python3 | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "python3 ->  [${V8}]"
V9=$(apt-cache policy python3-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "python3-dev ->  [${V9}]"
V10=$(apt-cache policy python3-pip | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "python3-pip ->  [${V10}]"
V11=$(apt-cache policy python3-venv | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "python3-venv ->  [${V11}]"
V12=$(apt-cache policy texlive | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "texlive ->  [${V12}]"
V13=$(apt-cache policy texlive-latex-extra | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "texlive-latex-extra ->  [${V13}]"
V14=$(apt-cache policy texlive-xetex | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "texlive-xetex ->  [${V14}]"
V15=$(apt-cache policy zlib1g-dev | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "zlib1g-dev ->  [${V15}]"
