#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: peek-developers/stable
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:peek-developers/stable
sudo apt-get update -y
# >>>> PKGS: peek
sudo apt-get install -y \
	peek
