#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > dos2unix
#		 > apt

printf "dos2unix > %s\n" "$(apt-cache policy dos2unix | grep Candidate | cut -d: -f2 | tr -d /" /")"
