#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: httrack
#		 > Template: apt

printf "webhttrack > %s\n" "$(apt-cache policy webhttrack | grep Installed | cut -d: -f2 | tr -d /" /")"
