#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PKGS: virtualbox virtualbox-dkms virtualbox-ext-pack virtualbox-guest-dkms
sudo apt-get install -y \
	virtualbox \
	virtualbox-dkms \
	virtualbox-ext-pack \
	virtualbox-guest-dkms
