#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo apt-get remove -y virtualbox
sudo apt-get remove -y virtualbox-dkms
sudo apt-get remove -y virtualbox-ext-pack
sudo apt-get remove -y virtualbox-guest-dkms
