#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy virtualbox | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "virtualbox ->  [${V0}]"
V1=$(apt-cache policy virtualbox-dkms | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "virtualbox-dkms ->  [${V1}]"
V2=$(apt-cache policy virtualbox-ext-pack | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "virtualbox-ext-pack ->  [${V2}]"
V3=$(apt-cache policy virtualbox-guest-dkms | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "virtualbox-guest-dkms ->  [${V3}]"
