#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: freecad-maintainers/freecad-stable
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
sudo apt-get update -y
# >>>> PKGS: checkinstall freecad freecad-common freecad-python3 git
sudo apt-get install -y \
	checkinstall \
	freecad \
	freecad-common \
	freecad-python3 \
	git
