#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo add-apt-repository --remove -y ppa:freecad-maintainers/freecad-stable
sudo apt-get remove -y checkinstall
sudo apt-get remove -y freecad
sudo apt-get remove -y freecad-common
sudo apt-get remove -y freecad-python3
sudo apt-get remove -y git
