#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'checkinstall' | grep -q "\[installed\]")
then
   echo "[checkinstall] -> [installed!]";
else
   echo "[checkinstall] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'freecad' | grep -q "\[installed\]")
then
   echo "[freecad] -> [installed!]";
else
   echo "[freecad] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'freecad-common' | grep -q "\[installed\]")
then
   echo "[freecad-common] -> [installed!]";
else
   echo "[freecad-common] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'freecad-python3' | grep -q "\[installed\]")
then
   echo "[freecad-python3] -> [installed!]";
else
   echo "[freecad-python3] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'git' | grep -q "\[installed\]")
then
   echo "[git] -> [installed!]";
else
   echo "[git] -> [NOT installed!]";
   missing=1;
fi
