#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy checkinstall | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "checkinstall ->  [${V0}]"
V1=$(apt-cache policy freecad | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "freecad ->  [${V1}]"
V2=$(apt-cache policy freecad-common | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "freecad-common ->  [${V2}]"
V3=$(apt-cache policy freecad-python3 | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "freecad-python3 ->  [${V3}]"
V4=$(apt-cache policy git | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "git ->  [${V4}]"
