#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy fonts-font-awesome | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "fonts-font-awesome ->  [${V0}]"
V1=$(apt-cache policy fonts-noto-color-emoji | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "fonts-noto-color-emoji ->  [${V1}]"
