#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: shotcut
#		 > Template: flatpak

flatpak install -y flathub org.shotcut.Shotcut
