#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: shotcut
#		 > Template: flatpak

printf "org.shotcut.Shotcut > %s\n" "$(flatpak info org.shotcut.Shotcut | grep Version | cut -d: -f2 | tr -d /" /")"
