#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: shotcut
#		 > Template: flatpak

flatpak uninstall org.shotcut.Shotcut  --delete-data
