#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: shotcut
#		 > Template: flatpak

printf "org.shotcut.Shotcut > %s\n" "$(flatpak search org.shotcut.Shotcut | head -n1 | cut -f4 | tr -d /" /")"
