#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > shotcut
#		 > flatpak

printf "org.shotcut.Shotcut > %s\n" "$(flatpak search org.shotcut.Shotcut | head -n1 | cut -f4 | tr -d /" /")"
