#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > INSTALL.SH
#		 > TeX Studio
#		 > apt

sudo apt-get install -y texlive-fonts-extra texlive-full texlive-latex-extra texlive-xetex texstudio
