#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: TeX Studio
#		 > Template: apt

printf "texlive-fonts-extra > %s\n" "$(apt-cache policy texlive-fonts-extra | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive-full > %s\n" "$(apt-cache policy texlive-full | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive-latex-extra > %s\n" "$(apt-cache policy texlive-latex-extra | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive-xetex > %s\n" "$(apt-cache policy texlive-xetex | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texstudio > %s\n" "$(apt-cache policy texstudio | grep Installed | cut -d: -f2 | tr -d /" /")"
