#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: TeX Studio
#		 > Template: apt

sudo apt-get remove -y texlive-fonts-extra texlive-full texlive-latex-extra texlive-xetex texstudio
