#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: curl
#		 > Template: apt

printf "curl > %s\n" "$(apt-cache policy curl | grep Candidate | cut -d: -f2 | tr -d /" /")"
