#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: source-highlight
#		 > Template: apt

printf "source-highlight > %s\n" "$(apt-cache policy source-highlight | grep Installed | cut -d: -f2 | tr -d /" /")"
