#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > source-highlight
#		 > apt

printf "source-highlight > %s\n" "$(apt-cache policy source-highlight | grep Installed | cut -d: -f2 | tr -d /" /")"
