#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: source-highlight
#		 > Template: apt

printf "source-highlight > %s\n" "$(apt-cache policy source-highlight | grep Candidate | cut -d: -f2 | tr -d /" /")"
