#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > source-highlight
#		 > apt

printf "source-highlight > %s\n" "$(apt-cache policy source-highlight | grep Candidate | cut -d: -f2 | tr -d /" /")"
