#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > watchman
#		 > apt

printf "watchman > %s\n" "$(apt-cache policy watchman | grep Candidate | cut -d: -f2 | tr -d /" /")"
