#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: watchman
#		 > Template: apt

printf "watchman > %s\n" "$(apt-cache policy watchman | grep Candidate | cut -d: -f2 | tr -d /" /")"
