#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

sudo add-apt-repository -y universe
sudo apt-get update -y
sudo apt-get install -y shutter

# <<<POST-AUTOGENERATED FILE - DO NOT MODIFY>>>
