#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: Shutter
#		 > Template: apt

printf "shutter > %s\n" "$(apt-cache policy shutter | grep Installed | cut -d: -f2 | tr -d /" /")"
