#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > Shutter
#		 > apt

printf "shutter > %s\n" "$(apt-cache policy shutter | grep Candidate | cut -d: -f2 | tr -d /" /")"
