#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Shutter
#		 > Template: apt

printf "shutter > %s\n" "$(apt-cache policy shutter | grep Candidate | cut -d: -f2 | tr -d /" /")"
