#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: xxh
#		 > Template: pipx

pipx list | grep installed | grep xxh-xxh | ts -s ' ' | cut -d' ' -f8
