#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > zip
#		 > apt

printf "zip > %s\n" "$(apt-cache policy zip | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "unzip > %s\n" "$(apt-cache policy unzip | grep Installed | cut -d: -f2 | tr -d /" /")"
