#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "zip > %s\n" "$(apt-cache policy zip | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "unzip > %s\n" "$(apt-cache policy unzip | grep Candidate | cut -d: -f2 | tr -d /" /")"
