#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: zip
#		 > Template: apt

printf "zip > %s\n" "$(apt-cache policy zip | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "unzip > %s\n" "$(apt-cache policy unzip | grep Candidate | cut -d: -f2 | tr -d /" /")"
