#!/usr/bin/env python3

"""
Only meant to be imported within cog
"""

# stdlib imports
import typing as T

SH_SHEBANG: T.Final[str] = "#!/usr/bin/env sh"

HEADER: T.Final[str] = "<<<AUTOGENERATED FILE - DO NOT MODIFY>>>"
