#!/usr/bin/env python3

"""
Only meant to be imported within cog
"""

# stdlib imports
import typing as T

SH_SHEBANG: T.Final[str] = "#!/usr/bin/env sh"

HEADER: T.Final[str] = "<<<AUTOGENERATED FILE - DO NOT MODIFY>>>"
POST_HEADER: T.Final[str] = "<<<POST-AUTOGENERATED FILE - DO NOT MODIFY>>>"

PRINTF_FMT: T.Final[str] = r"\e[0;34m%-6s\e[m\n"

SCRIPT_DEFAULTS: T.Final[str] = "\n".join(
    (
        r"INSTALLDIR=${INSTALLDIR:-${HOME}/.local/bin/}",
        r"BASHCOMP=${BASHCOMP:-${HOME}/.config/bash/bash_completion}",
        r"ZSHCOMP=${ZSHCOMP:-${HOME}/.config/zsh/completions}",
        r"TEMPDIR=$(mktemp -d -t XXXXXXXXXX)",
        r"FMT=\e[0;34m%-6s\e[m\n",
    )
)


# echo "Global wallpapers at /usr/share/backgrounds"
# echo "Local wallpapers at ~/.local/share/backgrounds"
#
#
# BGDIR=/usr/share/backgrounds
# mkdir -p ${BGDIR}
# IMG_URL='https://unsplash.com/photos/VzRKG0piEp8/download?force=true'
# sudo wget ${IMG_URL} --continue --output-document=${BGDIR}/wallpaper.jpg
# sudo convert ${BGDIR}/wallpaper.jpg ${BGDIR}/wallpaper.png
