#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: openVPN
#		 > Template: apt

sudo apt-get install -y easy-rsa network-manager-openvpn openvpn
