# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > INSTALL.SH
#		 > xournalpp
#		 > flatpak

#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

flatpak install flathub com.github.xournalpp.xournalpp

# <<<POST-AUTOGENERATED FILE - DO NOT MODIFY>>>
