#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: xournalpp
#		 > Template: flatpak

printf "com.github.xournalpp.xournalpp > %s\n" "$(flatpak info com.github.xournalpp.xournalpp | grep Version | cut -d: -f2 | tr -d /" /")"
