#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > xournalpp
#		 > flatpak

printf "com.github.xournalpp.xournalpp > %s\n" "$(flatpak info com.github.xournalpp.xournalpp | grep Version | cut -d: -f2 | tr -d /" /")"
