# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > REMOVE.SH
#		 > xournalpp
#		 > flatpak

#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > REMOVE.SH
#		 > xournalpp
#		 > flatpak

flatpak uninstall com.github.xournalpp.xournalpp  --delete-data
