#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: xournalpp
#		 > Template: flatpak

flatpak uninstall com.github.xournalpp.xournalpp  --delete-data
