#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: xournalpp
#		 > Template: flatpak

printf "com.github.xournalpp.xournalpp > %s\n" "$(flatpak search com.github.xournalpp.xournalpp | head -n1 | cut -f4 | tr -d /" /")"
