#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > xournalpp
#		 > flatpak

printf "com.github.xournalpp.xournalpp > %s\n" "$(flatpak search com.github.xournalpp.xournalpp | head -n1 | cut -f4 | tr -d /" /")"
