#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > KmCaster
#		 > flatpak

printf "com.whitemagicsoftware.kmcaster > %s\n" "$(flatpak info com.whitemagicsoftware.kmcaster | grep Version | cut -d: -f2 | tr -d /" /")"
