#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: KmCaster
#		 > Template: flatpak

printf "com.whitemagicsoftware.kmcaster > %s\n" "$(flatpak info com.whitemagicsoftware.kmcaster | grep Version | cut -d: -f2 | tr -d /" /")"
