#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: KmCaster
#		 > Template: flatpak

printf "com.whitemagicsoftware.kmcaster > %s\n" "$(flatpak search com.whitemagicsoftware.kmcaster | head -n1 | cut -f4 | tr -d /" /")"
