#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'dconf-editor' | grep -q "\[installed\]")
then
   echo "[dconf-editor] -> [installed!]";
else
   echo "[dconf-editor] -> [NOT installed!]";
   missing=1;
fi
