#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > ppa-purge
#		 > apt

printf "ppa-purge > %s\n" "$(apt-cache policy ppa-purge | grep Installed | cut -d: -f2 | tr -d /" /")"
