#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: ppa-purge
#		 > Template: apt

printf "ppa-purge > %s\n" "$(apt-cache policy ppa-purge | grep Candidate | cut -d: -f2 | tr -d /" /")"
