#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: paraview
#		 > Template: flatpak

flatpak install -y flathub org.paraview.ParaView
