#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > paraview
#		 > flatpak

printf "org.paraview.ParaView > %s\n" "$(flatpak info org.paraview.ParaView | grep Version | cut -d: -f2 | tr -d /" /")"
