#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: paraview
#		 > Template: flatpak

flatpak uninstall org.paraview.ParaView  --delete-data
