#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > paraview
#		 > flatpak

printf "org.paraview.ParaView > %s\n" "$(flatpak search org.paraview.ParaView | head -n1 | cut -f4 | tr -d /" /")"
