#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: paraview
#		 > Template: flatpak

printf "org.paraview.ParaView > %s\n" "$(flatpak search org.paraview.ParaView | head -n1 | cut -f4 | tr -d /" /")"
