#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: neofetch
#		 > Template: apt

printf "neofetch > %s\n" "$(apt-cache policy neofetch | grep Installed | cut -d: -f2 | tr -d /" /")"
