#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > neofetch
#		 > apt

printf "neofetch > %s\n" "$(apt-cache policy neofetch | grep Installed | cut -d: -f2 | tr -d /" /")"
