#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: neofetch
#		 > Template: apt

printf "neofetch > %s\n" "$(apt-cache policy neofetch | grep Candidate | cut -d: -f2 | tr -d /" /")"
