#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: xcwd
#		 > Template: apt

printf "xcwd > %s\n" "$(apt-cache policy xcwd | grep Installed | cut -d: -f2 | tr -d /" /")"
