#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: xcwd
#		 > Template: apt

printf "xcwd > %s\n" "$(apt-cache policy xcwd | grep Candidate | cut -d: -f2 | tr -d /" /")"
