#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > font-awesome
#		 > apt

printf "fonts-font-awesome > %s\n" "$(apt-cache policy fonts-font-awesome | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "fonts-noto-color-emoji > %s\n" "$(apt-cache policy fonts-noto-color-emoji | grep Installed | cut -d: -f2 | tr -d /" /")"
