#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: font-awesome
#		 > Template: apt

sudo apt-get remove -y fonts-font-awesome fonts-noto-color-emoji
