#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "fonts-font-awesome > %s\n" "$(apt-cache policy fonts-font-awesome | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "fonts-noto-color-emoji > %s\n" "$(apt-cache policy fonts-noto-color-emoji | grep Candidate | cut -d: -f2 | tr -d /" /")"
