#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: font-awesome
#		 > Template: apt

printf "fonts-font-awesome > %s\n" "$(apt-cache policy fonts-font-awesome | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "fonts-noto-color-emoji > %s\n" "$(apt-cache policy fonts-noto-color-emoji | grep Candidate | cut -d: -f2 | tr -d /" /")"
