#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > Java
#		 > apt

printf "default-jre > %s\n" "$(apt-cache policy default-jre | grep Installed | cut -d: -f2 | tr -d /" /")"
