#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Java
#		 > Template: apt

printf "default-jre > %s\n" "$(apt-cache policy default-jre | grep Candidate | cut -d: -f2 | tr -d /" /")"
