#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

sudo apt-get install -y flatpak gnome-software-plugin-flatpak

# <<<POST-AUTOGENERATED FILE - DO NOT MODIFY>>>

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo