#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: Flatpak
#		 > Template: apt

printf "flatpak > %s\n" "$(apt-cache policy flatpak | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "gnome-software-plugin-flatpak > %s\n" "$(apt-cache policy gnome-software-plugin-flatpak | grep Installed | cut -d: -f2 | tr -d /" /")"
