#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: Flatpak
#		 > Template: apt

sudo apt-get remove -y flatpak gnome-software-plugin-flatpak
