#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Flatpak
#		 > Template: apt

printf "flatpak > %s\n" "$(apt-cache policy flatpak | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "gnome-software-plugin-flatpak > %s\n" "$(apt-cache policy gnome-software-plugin-flatpak | grep Candidate | cut -d: -f2 | tr -d /" /")"
