#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "flatpak > %s\n" "$(apt-cache policy flatpak | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "gnome-software-plugin-flatpak > %s\n" "$(apt-cache policy gnome-software-plugin-flatpak | grep Candidate | cut -d: -f2 | tr -d /" /")"
