#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: yadm
#		 > Template: apt

printf "yadm > %s\n" "$(apt-cache policy yadm | grep Installed | cut -d: -f2 | tr -d /" /")"
