#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'openssh-server' | grep -q "\[installed\]")
then
   echo "[openssh-server] -> [installed!]";
else
   echo "[openssh-server] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'xauth' | grep -q "\[installed\]")
then
   echo "[xauth] -> [installed!]";
else
   echo "[xauth] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'xclip' | grep -q "\[installed\]")
then
   echo "[xclip] -> [installed!]";
else
   echo "[xclip] -> [NOT installed!]";
   missing=1;
fi
