#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy openssh-server | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "openssh-server ->  [${V0}]"
V1=$(apt-cache policy xauth | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "xauth ->  [${V1}]"
V2=$(apt-cache policy xclip | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "xclip ->  [${V2}]"
