#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo add-apt-repository --remove -y ppa:regolith-linux/release
sudo apt-get remove -y i3xrocks
sudo apt-get remove -y i3xrocks-battery
sudo apt-get remove -y i3xrocks-cpu-usage
sudo apt-get remove -y i3xrocks-next-workspace
sudo apt-get remove -y i3xrocks-rofication
sudo apt-get remove -y i3xrocks-time
sudo apt-get remove -y i3xrocks-todo
sudo apt-get remove -y regolith-desktop-standard
sudo apt-get remove -y regolith-i3xrocks-config
sudo apt-get remove -y regolith-look-ubuntu
