#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'i3xrocks' | grep -q "\[installed\]")
then
   echo "[i3xrocks] -> [installed!]";
else
   echo "[i3xrocks] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'i3xrocks-battery' | grep -q "\[installed\]")
then
   echo "[i3xrocks-battery] -> [installed!]";
else
   echo "[i3xrocks-battery] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'i3xrocks-cpu-usage' | grep -q "\[installed\]")
then
   echo "[i3xrocks-cpu-usage] -> [installed!]";
else
   echo "[i3xrocks-cpu-usage] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'i3xrocks-next-workspace' | grep -q "\[installed\]")
then
   echo "[i3xrocks-next-workspace] -> [installed!]";
else
   echo "[i3xrocks-next-workspace] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'i3xrocks-rofication' | grep -q "\[installed\]")
then
   echo "[i3xrocks-rofication] -> [installed!]";
else
   echo "[i3xrocks-rofication] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'i3xrocks-time' | grep -q "\[installed\]")
then
   echo "[i3xrocks-time] -> [installed!]";
else
   echo "[i3xrocks-time] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'i3xrocks-todo' | grep -q "\[installed\]")
then
   echo "[i3xrocks-todo] -> [installed!]";
else
   echo "[i3xrocks-todo] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'regolith-desktop-standard' | grep -q "\[installed\]")
then
   echo "[regolith-desktop-standard] -> [installed!]";
else
   echo "[regolith-desktop-standard] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'regolith-i3xrocks-config' | grep -q "\[installed\]")
then
   echo "[regolith-i3xrocks-config] -> [installed!]";
else
   echo "[regolith-i3xrocks-config] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'regolith-look-ubuntu' | grep -q "\[installed\]")
then
   echo "[regolith-look-ubuntu] -> [installed!]";
else
   echo "[regolith-look-ubuntu] -> [NOT installed!]";
   missing=1;
fi
