#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy i3xrocks | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks ->  [${V0}]"
V1=$(apt-cache policy i3xrocks-battery | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks-battery ->  [${V1}]"
V2=$(apt-cache policy i3xrocks-cpu-usage | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks-cpu-usage ->  [${V2}]"
V3=$(apt-cache policy i3xrocks-next-workspace | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks-next-workspace ->  [${V3}]"
V4=$(apt-cache policy i3xrocks-rofication | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks-rofication ->  [${V4}]"
V5=$(apt-cache policy i3xrocks-time | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks-time ->  [${V5}]"
V6=$(apt-cache policy i3xrocks-todo | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3xrocks-todo ->  [${V6}]"
V7=$(apt-cache policy regolith-desktop-standard | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "regolith-desktop-standard ->  [${V7}]"
V8=$(apt-cache policy regolith-i3xrocks-config | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "regolith-i3xrocks-config ->  [${V8}]"
V9=$(apt-cache policy regolith-look-ubuntu | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "regolith-look-ubuntu ->  [${V9}]"
