#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: gromit-mpx
#		 > Template: apt

printf "gromit-mpx > %s\n" "$(apt-cache policy gromit-mpx | grep Installed | cut -d: -f2 | tr -d /" /")"
