#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > gromit-mpx
#		 > apt

printf "nomacs > %s\n" "$(apt-cache policy nomacs | grep Installed | cut -d: -f2 | tr -d /" /")"
