#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: gromit-mpx
#		 > Template: apt

printf "gromit-mpx > %s\n" "$(apt-cache policy gromit-mpx | grep Candidate | cut -d: -f2 | tr -d /" /")"
