#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: fzf
#		 > Template: apt

printf "fzf > %s\n" "$(apt-cache policy fzf | grep Installed | cut -d: -f2 | tr -d /" /")"
