#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: fzf
#		 > Template: apt

printf "fzf > %s\n" "$(apt-cache policy fzf | grep Candidate | cut -d: -f2 | tr -d /" /")"
