#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: tree
#		 > Template: apt

printf "tree > %s\n" "$(apt-cache policy tree | grep Installed | cut -d: -f2 | tr -d /" /")"
