#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: tree
#		 > Template: apt

printf "tree > %s\n" "$(apt-cache policy tree | grep Candidate | cut -d: -f2 | tr -d /" /")"
