#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy gnome-tweak-tool | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "gnome-tweak-tool ->  [${V0}]"
V1=$(apt-cache policy gnome-tweaks | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "gnome-tweaks ->  [${V1}]"
