#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

    if $(snap list | cut -f1 -d' ' | tail -n +2 | grep -q 'slack' )
    then
       echo "[slack] -> [installed!]";
    else
       echo "[slack] -> [NOT installed!]";
       missing=1;
    fi
