#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: latex
#		 > Template: apt

sudo apt-get install -y texlive-latex-extra texlive-xetex
