#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: latex
#		 > Template: apt

printf "texlive-latex-extra > %s\n" "$(apt-cache policy texlive-latex-extra | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive-xetex > %s\n" "$(apt-cache policy texlive-xetex | grep Installed | cut -d: -f2 | tr -d /" /")"
