#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: latex
#		 > Template: apt

printf "texlive-latex-extra > %s\n" "$(apt-cache policy texlive-latex-extra | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "texlive-xetex > %s\n" "$(apt-cache policy texlive-xetex | grep Candidate | cut -d: -f2 | tr -d /" /")"
