#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: sxiv
#		 > Template: apt

printf "sxiv > %s\n" "$(apt-cache policy sxiv | grep Installed | cut -d: -f2 | tr -d /" /")"
