#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: sxiv
#		 > Template: apt

printf "sxiv > %s\n" "$(apt-cache policy sxiv | grep Candidate | cut -d: -f2 | tr -d /" /")"
