#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: sxiv
#		 > Template: apt

printf "sxiv > %s\n" "$(apt-cache policy sxiv | grep Candidate | cut -d: -f2 | tr -d /" /")"
