#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: pdfchain
#		 > Template: apt

printf "pdfchain > %s\n" "$(apt-cache policy pdfchain | grep Installed | cut -d: -f2 | tr -d /" /")"
