#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: pdfchain
#		 > Template: apt

printf "pdfchain > %s\n" "$(apt-cache policy pdfchain | grep Installed | cut -d: -f2 | tr -d /" /")"
