#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > pdfchain
#		 > apt

printf "pdfchain > %s\n" "$(apt-cache policy pdfchain | grep Candidate | cut -d: -f2 | tr -d /" /")"
