#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: pdfchain
#		 > Template: apt

printf "pdfchain > %s\n" "$(apt-cache policy pdfchain | grep Candidate | cut -d: -f2 | tr -d /" /")"
