#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > VSCodium
#		 > flatpak

printf "com.vscodium.codium > %s\n" "$(flatpak info com.vscodium.codium | grep Version | cut -d: -f2 | tr -d /" /")"
