#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: VSCodium
#		 > Template: flatpak

flatpak uninstall com.vscodium.codium  --delete-data
