#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: VSCodium
#		 > Template: flatpak

printf "com.vscodium.codium > %s\n" "$(flatpak search com.vscodium.codium | head -n1 | cut -f4 | tr -d /" /")"
