#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "neovim > %s\n" "$(apt-cache policy neovim | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "python3-neovim > %s\n" "$(apt-cache policy python3-neovim | grep Installed | cut -d: -f2 | tr -d /" /")"
