#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: xournalpp
#		 > Template: apt

printf "xournalpp > %s\n" "$(apt-cache policy xournalpp | grep Installed | cut -d: -f2 | tr -d /" /")"
