#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > xournalpp
#		 > apt

printf "xournalpp > %s\n" "$(apt-cache policy xournalpp | grep Candidate | cut -d: -f2 | tr -d /" /")"
