#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy redshift | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "redshift ->  [${V0}]"
V1=$(apt-cache policy redshift-gtk | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "redshift-gtk ->  [${V1}]"
