#!/usr/bin/env sh


# AUTOGENERATED FILE! DO NOT MODIFY!


printf "[%s]\t%s\n" `[ $(apt-cache pkgnames | grep "p7zip-full" ) ] && echo "1" || echo "0"` "p7zip-full"
printf "[%s]\t%s\n" `[ $(apt-cache pkgnames | grep "p7zip-rar" ) ] && echo "1" || echo "0"` "p7zip-rar"
