#!/usr/bin/env sh


# AUTOGENERATED FILE! DO NOT MODIFY!

printf "[%s]\t%s\n" $(apt-cache policy "p7zip-full" | grep Candidate: | cut -d: -f2 | xargs) "p7zip-full"
printf "[%s]\t%s\n" $(apt-cache policy "p7zip-rar" | grep Candidate: | cut -d: -f2 | xargs) "p7zip-rar"
