#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > pygments
#		 > apt

printf "imagemagick > %s\n" "$(apt-cache policy imagemagick | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "ghostscript > %s\n" "$(apt-cache policy ghostscript | grep Installed | cut -d: -f2 | tr -d /" /")"
