#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "imagemagick > %s\n" "$(apt-cache policy imagemagick | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "ghostscript > %s\n" "$(apt-cache policy ghostscript | grep Candidate | cut -d: -f2 | tr -d /" /")"
