#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'python3-pygments' | grep -q "\[installed\]")
then
   echo "[python3-pygments] -> [installed!]";
else
   echo "[python3-pygments] -> [NOT installed!]";
   missing=1;
fi
