#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'software-properties-common' | grep -q "\[installed\]")
then
   echo "[software-properties-common] -> [installed!]";
else
   echo "[software-properties-common] -> [NOT installed!]";
   missing=1;
fi
