#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy software-properties-common | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "software-properties-common ->  [${V0}]"
