#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > Blender
#		 > apt

printf "blender > %s\n" "$(apt-cache policy blender | grep Candidate | cut -d: -f2 | tr -d /" /")"
