#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: aptitude
#		 > Template: apt

printf "aptitude > %s\n" "$(apt-cache policy aptitude | grep Installed | cut -d: -f2 | tr -d /" /")"
