#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: aptitude
#		 > Template: apt

printf "aptitude > %s\n" "$(apt-cache policy aptitude | grep Candidate | cut -d: -f2 | tr -d /" /")"
