#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: aptitude
#		 > Template: apt

printf "aptitude > %s\n" "$(apt-cache policy aptitude | grep Candidate | cut -d: -f2 | tr -d /" /")"
