#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > aptitude
#		 > apt

printf "aptitude > %s\n" "$(apt-cache policy aptitude | grep Candidate | cut -d: -f2 | tr -d /" /")"
