#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: Firefox
#		 > Template: flatpak

printf "org.mozilla.firefox > %s\n" "$(flatpak info org.mozilla.firefox | grep Version | cut -d: -f2 | tr -d /" /")"
