#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: Firefox
#		 > Template: flatpak

flatpak uninstall org.mozilla.firefox  --delete-data
