#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Firefox
#		 > Template: flatpak

printf "org.mozilla.firefox > %s\n" "$(flatpak search org.mozilla.firefox | head -n1 | cut -f4 | tr -d /" /")"
