#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > Calibre
#		 > flatpak

printf "com.calibre_ebook.calibre > %s\n" "$(flatpak info com.calibre_ebook.calibre | grep Version | cut -d: -f2 | tr -d /" /")"
