#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: lmms
#		 > Template: apt

printf "lmms > %s\n" "$(apt-cache policy lmms | grep Installed | cut -d: -f2 | tr -d /" /")"
