#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'trash-cli' | grep -q "\[installed\]")
then
   echo "[trash-cli] -> [installed!]";
else
   echo "[trash-cli] -> [NOT installed!]";
   missing=1;
fi
