#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: ncdu
#		 > Template: apt

printf "ncdu > %s\n" "$(apt-cache policy ncdu | grep Installed | cut -d: -f2 | tr -d /" /")"
