#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: ncdu
#		 > Template: apt

printf "ncdu > %s\n" "$(apt-cache policy ncdu | grep Candidate | cut -d: -f2 | tr -d /" /")"
