#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Sys
#		 > Template: apt

printf "sysprof > %s\n" "$(apt-cache policy sysprof | grep Candidate | cut -d: -f2 | tr -d /" /")"
