#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: doas
#		 > Template: apt

printf "doas > %s\n" "$(apt-cache policy doas | grep Candidate | cut -d: -f2 | tr -d /" /")"
