#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > kooha
#		 > flatpak

printf "io.github.seadve.Kooha > %s\n" "$(flatpak info io.github.seadve.Kooha | grep Version | cut -d: -f2 | tr -d /" /")"
