#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: kooha
#		 > Template: flatpak

printf "io.github.seadve.Kooha > %s\n" "$(flatpak info io.github.seadve.Kooha | grep Version | cut -d: -f2 | tr -d /" /")"
