#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: kooha
#		 > Template: flatpak

printf "io.github.seadve.Kooha > %s\n" "$(flatpak search io.github.seadve.Kooha | head -n1 | cut -f4 | tr -d /" /")"
