#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > kooha
#		 > flatpak

printf "io.github.seadve.Kooha > %s\n" "$(flatpak search io.github.seadve.Kooha | head -n1 | cut -f4 | tr -d /" /")"
