#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: flameshot
#		 > Template: apt

printf "flameshot > %s\n" "$(apt-cache policy flameshot | grep Installed | cut -d: -f2 | tr -d /" /")"
