#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > flameshot
#		 > apt

printf "flameshot > %s\n" "$(apt-cache policy flameshot | grep Installed | cut -d: -f2 | tr -d /" /")"
