#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: firewall-gui
#		 > Template: apt

printf "gufw > %s\n" "$(apt-cache policy gufw | grep Candidate | cut -d: -f2 | tr -d /" /")"
