#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > firewall-gui
#		 > apt

printf "gufw > %s\n" "$(apt-cache policy gufw | grep Candidate | cut -d: -f2 | tr -d /" /")"
