#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: wget
#		 > Template: apt

printf "wget > %s\n" "$(apt-cache policy wget | grep Installed | cut -d: -f2 | tr -d /" /")"
