#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: python
#		 > Template: apt

sudo apt-get install -y build-essential libffi-dev libpq-dev libssl-dev libxml2-dev libxslt1-dev pandoc pandoc-citeproc python3 python3-dev python3-pip python3-venv texlive texlive-latex-extra texlive-xetex zlib1g-dev
