#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: python
#		 > Template: apt

printf "build-essential > %s\n" "$(apt-cache policy build-essential | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "libffi-dev > %s\n" "$(apt-cache policy libffi-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "libpq-dev > %s\n" "$(apt-cache policy libpq-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "libssl-dev > %s\n" "$(apt-cache policy libssl-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "libxml2-dev > %s\n" "$(apt-cache policy libxml2-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "libxslt1-dev > %s\n" "$(apt-cache policy libxslt1-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "pandoc > %s\n" "$(apt-cache policy pandoc | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "pandoc-citeproc > %s\n" "$(apt-cache policy pandoc-citeproc | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "python3 > %s\n" "$(apt-cache policy python3 | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "python3-dev > %s\n" "$(apt-cache policy python3-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "python3-pip > %s\n" "$(apt-cache policy python3-pip | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "python3-venv > %s\n" "$(apt-cache policy python3-venv | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive > %s\n" "$(apt-cache policy texlive | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive-latex-extra > %s\n" "$(apt-cache policy texlive-latex-extra | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "texlive-xetex > %s\n" "$(apt-cache policy texlive-xetex | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "zlib1g-dev > %s\n" "$(apt-cache policy zlib1g-dev | grep Installed | cut -d: -f2 | tr -d /" /")"
