#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > python
#		 > apt

printf "build-essential > %s\n" "$(apt-cache policy build-essential | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "libffi-dev > %s\n" "$(apt-cache policy libffi-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "libpq-dev > %s\n" "$(apt-cache policy libpq-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "libssl-dev > %s\n" "$(apt-cache policy libssl-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "libxml2-dev > %s\n" "$(apt-cache policy libxml2-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "libxslt1-dev > %s\n" "$(apt-cache policy libxslt1-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "pandoc > %s\n" "$(apt-cache policy pandoc | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "pandoc-citeproc > %s\n" "$(apt-cache policy pandoc-citeproc | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "python3 > %s\n" "$(apt-cache policy python3 | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "python3-dev > %s\n" "$(apt-cache policy python3-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "python3-pip > %s\n" "$(apt-cache policy python3-pip | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "python3-venv > %s\n" "$(apt-cache policy python3-venv | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "texlive > %s\n" "$(apt-cache policy texlive | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "texlive-latex-extra > %s\n" "$(apt-cache policy texlive-latex-extra | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "texlive-xetex > %s\n" "$(apt-cache policy texlive-xetex | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "zlib1g-dev > %s\n" "$(apt-cache policy zlib1g-dev | grep Candidate | cut -d: -f2 | tr -d /" /")"
