#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: software-properties-common
#		 > Template: apt

sudo apt-get install -y software-properties-common
