#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: software-properties-common
#		 > Template: apt

printf "software-properties-common > %s\n" "$(apt-cache policy software-properties-common | grep Installed | cut -d: -f2 | tr -d /" /")"
