#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > software-properties-common
#		 > apt

printf "software-properties-common > %s\n" "$(apt-cache policy software-properties-common | grep Installed | cut -d: -f2 | tr -d /" /")"
