#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: software-properties-common
#		 > Template: apt

sudo apt-get remove -y software-properties-common
