#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "software-properties-common > %s\n" "$(apt-cache policy software-properties-common | grep Candidate | cut -d: -f2 | tr -d /" /")"
