#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: CMake
#		 > Template: apt

sudo apt-get install -y cmake cmake-curses-gui cmake-qt-gui
