#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: CMake
#		 > Template: apt

printf "cmake > %s\n" "$(apt-cache policy cmake | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "cmake-curses-gui > %s\n" "$(apt-cache policy cmake-curses-gui | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "cmake-qt-gui > %s\n" "$(apt-cache policy cmake-qt-gui | grep Installed | cut -d: -f2 | tr -d /" /")"
