#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: CMake
#		 > Template: apt

printf "cmake > %s\n" "$(apt-cache policy cmake | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "cmake-curses-gui > %s\n" "$(apt-cache policy cmake-curses-gui | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "cmake-qt-gui > %s\n" "$(apt-cache policy cmake-qt-gui | grep Candidate | cut -d: -f2 | tr -d /" /")"
