#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: tidal-hifi
#		 > Template: flatpak

flatpak install -y flathub com.mastermindzh.tidal-hifi
