#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > tidal-hifi
#		 > flatpak

printf "com.mastermindzh.tidal-hifi > %s\n" "$(flatpak info com.mastermindzh.tidal-hifi | grep Version | cut -d: -f2 | tr -d /" /")"
