#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: tidal-hifi
#		 > Template: flatpak

flatpak uninstall com.mastermindzh.tidal-hifi  --delete-data
