#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo add-apt-repository --remove -y ppa:linuxuprising/apps
sudo apt-get remove -y tlp
sudo apt-get remove -y tlp-rdw
sudo apt-get remove -y tlpui
