#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'tlp' | grep -q "\[installed\]")
then
   echo "[tlp] -> [installed!]";
else
   echo "[tlp] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'tlp-rdw' | grep -q "\[installed\]")
then
   echo "[tlp-rdw] -> [installed!]";
else
   echo "[tlp-rdw] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'tlpui' | grep -q "\[installed\]")
then
   echo "[tlpui] -> [installed!]";
else
   echo "[tlpui] -> [NOT installed!]";
   missing=1;
fi
