#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy tlp | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "tlp ->  [${V0}]"
V1=$(apt-cache policy tlp-rdw | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "tlp-rdw ->  [${V1}]"
V2=$(apt-cache policy tlpui | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "tlpui ->  [${V2}]"
