#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: PDF Arranger
#		 > Template: flatpak

flatpak install -y flathub com.github.jeromerobert.pdfarranger
