#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: PDF Arranger
#		 > Template: flatpak

printf "com.github.jeromerobert.pdfarranger > %s\n" "$(flatpak info com.github.jeromerobert.pdfarranger | grep Version | cut -d: -f2 | tr -d /" /")"
