#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: PDF Arranger
#		 > Template: flatpak

flatpak uninstall com.github.jeromerobert.pdfarranger  --delete-data
