#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: nomacs
#		 > Template: apt

printf "nomacs > %s\n" "$(apt-cache policy nomacs | grep Installed | cut -d: -f2 | tr -d /" /")"
