#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: trash-cli
#		 > Template: apt

printf "trash-cli > %s\n" "$(apt-cache policy trash-cli | grep Installed | cut -d: -f2 | tr -d /" /")"
