#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: trash-cli
#		 > Template: apt

printf "trash-cli > %s\n" "$(apt-cache policy trash-cli | grep Candidate | cut -d: -f2 | tr -d /" /")"
