#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > trash-cli
#		 > apt

printf "trash-cli > %s\n" "$(apt-cache policy trash-cli | grep Candidate | cut -d: -f2 | tr -d /" /")"
