#!/usr/bin/env sh

# [[[cog
# import cog
#
# def split(long_string:str)->list[str]:
#     long_string=long_string.replace('"','').replace("'","").strip()
#     if not long_string:
#         return []
#     return [p.strip() for p in long_string.split(',')]
# 
# cog.outl("AUTOGENERATED FILE! DO NOT MODIFY!")
# ]]]
# [[[end]]]


# [[[cog
# PPA_LIST=split(PPAS)
# if PPA_LIST:
#     cog.outl("sudo add-apt-repository --remove " + " ".join(PPA_LIST))
# ]]]
# [[[end]]]


# [[[cog
# PKG_LIST=split(PKGS)
# if not PKG_LIST:
#     raise ValueError()
# cog.outl("sudo apt-get remove -y " + " ".join(split(PKGS)))
# ]]]
# [[[end]]]
