#!/usr/bin/env sh

# [[[cog
# import cog
# import subprocess
#
# def split(long_string:str)->list[str]:
#     long_string=long_string.replace('"','').replace("'","").strip()
#     if not long_string:
#         return []
#     return [p.strip() for p in long_string.split(',')]
#
# PKG_LIST=split(PKGS)
# 
# cog.outl("AUTOGENERATED FILE! DO NOT MODIFY!")
# ]]]
# [[[end]]]


# [[[cog
# p = subprocess.run(["apt-cache", "policy"] + PKG_LIST, capture_output=True)
# stdout_lines = p.stdout.decode('utf-8').splitlines()
# 
# local_map=dict()
# upstream_map=dict()
# 
# for pkg in PKG_LIST:
#     title = f"{pkg}:"
#     try:
#         idx = next(idx for idx, l in enumerate(stdout_lines) if l == title)
#     except StopIteration:
#         continue
#     local_ver_idx = idx + 1
#     upstream_ver_idx = idx + 2
# 
#     def get_ver(idx: int) -> str:
#         return ' '.join(stdout_lines[idx].split(":")[1:]).strip()
# 
#     local_map[pkg]= get_ver(idx + 1)
#     upstream_map[pkg]= get_ver(idx + 2)
# 
# ]]]
# [[[end]]]


# [[[cog
#
# def print_vers(d:dict[str,str])->None:
#     for pkg in PKG_LIST:
#         cog.outl(f"{pkg: <20} >  {d.get(pkg,'')}")
#
# print_vers(upstream_map)
# # ]]]
# [[[end]]]

