#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "p7zip-full > %s\n" "$(apt-cache policy p7zip-full | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "p7zip-rar > %s\n" "$(apt-cache policy p7zip-rar | grep Installed | cut -d: -f2 | tr -d /" /")"
