#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: 7zip
#		 > Template: apt

printf "p7zip-full > %s\n" "$(apt-cache policy p7zip-full | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "p7zip-rar > %s\n" "$(apt-cache policy p7zip-rar | grep Candidate | cut -d: -f2 | tr -d /" /")"
