#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > 7zip
#		 > apt

printf "p7zip-full > %s\n" "$(apt-cache policy p7zip-full | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "p7zip-rar > %s\n" "$(apt-cache policy p7zip-rar | grep Candidate | cut -d: -f2 | tr -d /" /")"
