#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: jq
#		 > Template: apt

printf "jq > %s\n" "$(apt-cache policy jq | grep Installed | cut -d: -f2 | tr -d /" /")"
