#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: jq
#		 > Template: apt

printf "jq > %s\n" "$(apt-cache policy jq | grep Installed | cut -d: -f2 | tr -d /" /")"
