#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: lua
#		 > Template: apt

printf "lua5.3 > %s\n" "$(apt-cache policy lua5.3 | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "luarocks > %s\n" "$(apt-cache policy luarocks | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "luajit > %s\n" "$(apt-cache policy luajit | grep Candidate | cut -d: -f2 | tr -d /" /")"
