#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Firefox
#		 > Template: apt

printf "firefox > %s\n" "$(apt-cache policy firefox | grep Candidate | cut -d: -f2 | tr -d /" /")"
