#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

flatpak install flathub io.neovim.nvim

# <<<POST-AUTOGENERATED FILE - DO NOT MODIFY>>>

# TODO
# https://github.com/neovim/neovim/wiki/Installing-Neovim#flatpak
