#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > INSTALL.SH
#		 > neovim
#		 > flatpak

flatpak install -y flathub io.neovim.nvim

# <<<POST STAGE>>>

# TODO
# https://github.com/neovim/neovim/wiki/Installing-Neovim#flatpak
