#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: neovim
#		 > Template: flatpak

flatpak install -y flathub io.neovim.nvim

# <<<POST STAGE>>>

# TODO
# https://github.com/neovim/neovim/wiki/Installing-Neovim#flatpak
