#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: neovim
#		 > Template: flatpak

printf "io.neovim.nvim > %s\n" "$(flatpak info io.neovim.nvim | grep Version | cut -d: -f2 | tr -d /" /")"
