#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: neovim
#		 > Template: flatpak

printf "io.neovim.nvim > %s\n" "$(flatpak search io.neovim.nvim | head -n1 | cut -f4 | tr -d /" /")"
