#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > neovim
#		 > flatpak

printf "io.neovim.nvim > %s\n" "$(flatpak search io.neovim.nvim | head -n1 | cut -f4 | tr -d /" /")"
