#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "gnome-tweak-tool > %s\n" "$(apt-cache policy gnome-tweak-tool | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "gnome-tweaks > %s\n" "$(apt-cache policy gnome-tweaks | grep Installed | cut -d: -f2 | tr -d /" /")"
