#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: gnome-tweaks
#		 > Template: apt

sudo apt-get remove -y gnome-tweak-tool gnome-tweaks
