#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: gnome-tweaks
#		 > Template: apt

printf "gnome-tweak-tool > %s\n" "$(apt-cache policy gnome-tweak-tool | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "gnome-tweaks > %s\n" "$(apt-cache policy gnome-tweaks | grep Candidate | cut -d: -f2 | tr -d /" /")"
