#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: moreutils
#		 > Template: apt

printf "moreutils > %s\n" "$(apt-cache policy moreutils | grep Installed | cut -d: -f2 | tr -d /" /")"
