#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > moreutils
#		 > apt

printf "moreutils > %s\n" "$(apt-cache policy moreutils | grep Candidate | cut -d: -f2 | tr -d /" /")"
