#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: dunst
#		 > Template: apt

printf "dunst > %s\n" "$(apt-cache policy dunst | grep Installed | cut -d: -f2 | tr -d /" /")"
