#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > ssh
#		 > apt

printf "openssh-server > %s\n" "$(apt-cache policy openssh-server | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "xauth > %s\n" "$(apt-cache policy xauth | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "xclip > %s\n" "$(apt-cache policy xclip | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "xcl > %s\n" "$(apt-cache policy xcl | grep Installed | cut -d: -f2 | tr -d /" /")"
