#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: ssh
#		 > Template: apt

printf "openssh-server > %s\n" "$(apt-cache policy openssh-server | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "xauth > %s\n" "$(apt-cache policy xauth | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "xclip > %s\n" "$(apt-cache policy xclip | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "xcl > %s\n" "$(apt-cache policy xcl | grep Candidate | cut -d: -f2 | tr -d /" /")"
