#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: dconf-editor
#		 > Template: apt

printf "dconf-editor > %s\n" "$(apt-cache policy dconf-editor | grep Installed | cut -d: -f2 | tr -d /" /")"
