#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > dconf-editor
#		 > apt

printf "dconf-editor > %s\n" "$(apt-cache policy dconf-editor | grep Installed | cut -d: -f2 | tr -d /" /")"
