#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: dconf-editor
#		 > Template: apt

printf "dconf-editor > %s\n" "$(apt-cache policy dconf-editor | grep Candidate | cut -d: -f2 | tr -d /" /")"
