#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: shellcheck
#		 > Template: apt

printf "shellcheck > %s\n" "$(apt-cache policy shellcheck | grep Installed | cut -d: -f2 | tr -d /" /")"
