#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > shellcheck
#		 > apt

printf "shellcheck > %s\n" "$(apt-cache policy shellcheck | grep Installed | cut -d: -f2 | tr -d /" /")"
