#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > shellcheck
#		 > apt

printf "shellcheck > %s\n" "$(apt-cache policy shellcheck | grep Candidate | cut -d: -f2 | tr -d /" /")"
