#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: ripgrep
#		 > Template: apt

printf "ripgrep > %s\n" "$(apt-cache policy ripgrep | grep Installed | cut -d: -f2 | tr -d /" /")"
