#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: ripgrep
#		 > Template: apt

printf "ripgrep > %s\n" "$(apt-cache policy ripgrep | grep Installed | cut -d: -f2 | tr -d /" /")"
