#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > ripgrep
#		 > apt

printf "ripgrep > %s\n" "$(apt-cache policy ripgrep | grep Candidate | cut -d: -f2 | tr -d /" /")"
