#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: ripgrep
#		 > Template: apt

printf "ripgrep > %s\n" "$(apt-cache policy ripgrep | grep Candidate | cut -d: -f2 | tr -d /" /")"
