#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > KeePassXC
#		 > flatpak

printf "org.keepassxc.KeePassXC > %s\n" "$(flatpak search org.keepassxc.KeePassXC | head -n1 | cut -f4 | tr -d /" /")"
