#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy easy-rsa | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "easy-rsa ->  [${V0}]"
V1=$(apt-cache policy network-manager-openvpn | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "network-manager-openvpn ->  [${V1}]"
V2=$(apt-cache policy openvpn | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "openvpn ->  [${V2}]"
