#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: nmap
#		 > Template: apt

printf "nmap > %s\n" "$(apt-cache policy nmap | grep Installed | cut -d: -f2 | tr -d /" /")"
