#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: nmap
#		 > Template: apt

printf "nmap > %s\n" "$(apt-cache policy nmap | grep Candidate | cut -d: -f2 | tr -d /" /")"
