#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: grsync
#		 > Template: apt

printf "grsync > %s\n" "$(apt-cache policy grsync | grep Installed | cut -d: -f2 | tr -d /" /")"
