#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: paraview
#		 > Template: apt

printf "paraview > %s\n" "$(apt-cache policy paraview | grep Installed | cut -d: -f2 | tr -d /" /")"
