#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > paraview
#		 > apt

printf "paraview > %s\n" "$(apt-cache policy paraview | grep Installed | cut -d: -f2 | tr -d /" /")"
