#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > imagemagick
#		 > apt

printf "imagemagick > %s\n" "$(apt-cache policy imagemagick | grep Installed | cut -d: -f2 | tr -d /" /")"
