#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > imagemagick
#		 > apt

printf "python3-pygments > %s\n" "$(apt-cache policy python3-pygments | grep Candidate | cut -d: -f2 | tr -d /" /")"
