#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: imagemagick
#		 > Template: apt

printf "imagemagick > %s\n" "$(apt-cache policy imagemagick | grep Candidate | cut -d: -f2 | tr -d /" /")"
