#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: kgilmer/speed-ricer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:kgilmer/speed-ricer
sudo apt-get update -y
# >>>> PKGS: arandr compton feh fonts-source-code-pro-ttf htop i3-gaps i3-gaps-wm i3-snapshot i3blocks lxappearance moka-icon-theme nordic rofi xbacklight
sudo apt-get install -y \
	arandr \
	compton \
	feh \
	fonts-source-code-pro-ttf \
	htop \
	i3-gaps \
	i3-gaps-wm \
	i3-snapshot \
	i3blocks \
	lxappearance \
	moka-icon-theme \
	nordic \
	rofi \
	xbacklight
