#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo add-apt-repository --remove -y ppa:kgilmer/speed-ricer
sudo apt-get remove -y arandr
sudo apt-get remove -y compton
sudo apt-get remove -y feh
sudo apt-get remove -y fonts-source-code-pro-ttf
sudo apt-get remove -y htop
sudo apt-get remove -y i3-gaps
sudo apt-get remove -y i3-gaps-wm
sudo apt-get remove -y i3-snapshot
sudo apt-get remove -y i3blocks
sudo apt-get remove -y lxappearance
sudo apt-get remove -y moka-icon-theme
sudo apt-get remove -y nordic
sudo apt-get remove -y rofi
sudo apt-get remove -y xbacklight
