#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: exfat
#		 > Template: apt

printf "exfat-fuse > %s\n" "$(apt-cache policy exfat-fuse | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "exfat-utils > %s\n" "$(apt-cache policy exfat-utils | grep Installed | cut -d: -f2 | tr -d /" /")"
