#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: exfat
#		 > Template: apt

printf "exfat-fuse > %s\n" "$(apt-cache policy exfat-fuse | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "exfat-utils > %s\n" "$(apt-cache policy exfat-utils | grep Candidate | cut -d: -f2 | tr -d /" /")"
