#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > exfat
#		 > apt

printf "exfat-fuse > %s\n" "$(apt-cache policy exfat-fuse | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "exfat-utils > %s\n" "$(apt-cache policy exfat-utils | grep Candidate | cut -d: -f2 | tr -d /" /")"
