#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > clamav
#		 > apt

printf "clamav > %s\n" "$(apt-cache policy clamav | grep Installed | cut -d: -f2 | tr -d /" /")"
printf "clamav-daemon > %s\n" "$(apt-cache policy clamav-daemon | grep Installed | cut -d: -f2 | tr -d /" /")"
