#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: clamav
#		 > Template: apt

printf "clamav > %s\n" "$(apt-cache policy clamav | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "clamav-daemon > %s\n" "$(apt-cache policy clamav-daemon | grep Candidate | cut -d: -f2 | tr -d /" /")"
