#!/usr/bin/env sh

# <<<AUTOGENERATED FILE - DO NOT MODIFY>>>

printf "clamav > %s\n" "$(apt-cache policy clamav | grep Candidate | cut -d: -f2 | tr -d /" /")"
printf "clamav-daemon > %s\n" "$(apt-cache policy clamav-daemon | grep Candidate | cut -d: -f2 | tr -d /" /")"
