#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: andreasbutti/xournalpp-master
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:andreasbutti/xournalpp-master
sudo apt-get update -y
# >>>> PKGS: xournalpp
sudo apt-get install -y \
	xournalpp
