#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PKGS: arandr compton feh htop i3 i3blocks i3lock-fancy lxappearance rofi suckless-tools xbacklight
sudo apt-get install -y \
	arandr \
	compton \
	feh \
	htop \
	i3 \
	i3blocks \
	i3lock-fancy \
	lxappearance \
	rofi \
	suckless-tools \
	xbacklight
