#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

sudo apt-get remove -y arandr
sudo apt-get remove -y compton
sudo apt-get remove -y feh
sudo apt-get remove -y htop
sudo apt-get remove -y i3
sudo apt-get remove -y i3blocks
sudo apt-get remove -y i3lock-fancy
sudo apt-get remove -y lxappearance
sudo apt-get remove -y rofi
sudo apt-get remove -y suckless-tools
sudo apt-get remove -y xbacklight
