#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy arandr | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "arandr ->  [${V0}]"
V1=$(apt-cache policy compton | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "compton ->  [${V1}]"
V2=$(apt-cache policy feh | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "feh ->  [${V2}]"
V3=$(apt-cache policy htop | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "htop ->  [${V3}]"
V4=$(apt-cache policy i3 | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3 ->  [${V4}]"
V5=$(apt-cache policy i3blocks | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3blocks ->  [${V5}]"
V6=$(apt-cache policy i3lock-fancy | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "i3lock-fancy ->  [${V6}]"
V7=$(apt-cache policy lxappearance | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "lxappearance ->  [${V7}]"
V8=$(apt-cache policy rofi | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "rofi ->  [${V8}]"
V9=$(apt-cache policy suckless-tools | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "suckless-tools ->  [${V9}]"
V10=$(apt-cache policy xbacklight | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "xbacklight ->  [${V10}]"
