#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'unzip' | grep -q "\[installed\]")
then
   echo "[unzip] -> [installed!]";
else
   echo "[unzip] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'zip' | grep -q "\[installed\]")
then
   echo "[zip] -> [installed!]";
else
   echo "[zip] -> [NOT installed!]";
   missing=1;
fi
