#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

V0=$(apt-cache policy unzip | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "unzip ->  [${V0}]"
V1=$(apt-cache policy zip | grep Candidate: | rev | cut -d: -f1 | rev | cut -d- -f1)
echo "zip ->  [${V1}]"
