#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY
# https://j2live.ttl255.com/



TMP_DEB=/tmp/google-chrome.deb

sudo apt install -y wget
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb --continue --output-document=${TMP_DEB}
sudo apt install ${TMP_DEB}
