#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: pinta
#		 > Template: apt

printf "pinta > %s\n" "$(apt-cache policy pinta | grep Candidate | cut -d: -f2 | tr -d /" /")"
