#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: Git Cola
#		 > Template: flatpak

flatpak install -y flathub com.github.git_cola.git-cola
