#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: Git Cola
#		 > Template: flatpak

printf "com.github.git_cola.git-cola > %s\n" "$(flatpak search com.github.git_cola.git-cola | head -n1 | cut -f4 | tr -d /" /")"
