#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: shutter/ppa
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:shutter/ppa
sudo apt-get update -y
# >>>> PKGS: shutter
sudo apt-get install -y \
	shutter
