#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: cmus
#		 > Template: apt

printf "cmus > %s\n" "$(apt-cache policy cmus | grep Installed | cut -d: -f2 | tr -d /" /")"
