#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: cmus
#		 > Template: apt

printf "cmus > %s\n" "$(apt-cache policy cmus | grep Candidate | cut -d: -f2 | tr -d /" /")"
