#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: neovim
#		 > Template: bin

# Variables
INSTALL_DST="${INSTALL_DST:-${HOME}/.local/bin/}"
BASHCOMP_P="${BASHCOMP_P:-${HOME}/.config/bash/bash_completion}"
ZSHCOMP="${ZSHCOMP:-${HOME}/.config/zsh/completions}"
TEMPDIR="$(mktemp -d -t XXXXXXXXXX)"
FMT='\e[0;34m%-6s\e[m\n'
# Commands
DLTMP=$(mktemp -d -t jumpstart-XXXXXXXXXX) \
&& cd "${DLTMP}" \
&& printf "\e[0;34m%-6s\e[m\n" "Downloading to $(realpath .)" \
&& URL=$(curl --silent 'https://api.github.com/repos/neovim/neovim/releases/latest' | jq '..|.browser_download_url? | select( . != null )' | tr -d '"' | grep --ignore-case '\.appimage"') \
&& curl -jLO "${URL}" \
&& DLFILE=$(ls . | head -n1) \
&& SRCPATH=$( find . -type f | grep --ignore-case 'nvim' ) \
&& sudo chmod +x "${SRCPATH}" \
&& sudo mv "${SRCPATH}" "${INSTALL_DST}/nvim"

# <<<POST STAGE>>>

printf "\e[0;34m%-6s\e[m\n" "Download_icon" \
&& sudo wget "https://raw.githubusercontent.com/neovim/neovim.github.io/master/logos/neovim-mark.svg" --continue --output-document="/usr/share/icons/neovim.svg"
printf "\e[0;34m%-6s\e[m\n" "Download kickstart nvim init.lua" \
&& curl -JL "https://raw.githubusercontent.com/nvim-lua/kickstart.nvim/master/init.lua" -o "${HOME}/.config/nvim/init.lua.lua"

# Set up config dir
mkdir -p ${HOME}/.config/nvim
cd ${HOME}/.config/nvim

# Run :PackerInstall
# Start nvim and run `:PackerInstall` (ignore the errors)
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# Restart neovim -> install plugins
# Restart neovim -> install LSPs
