#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

# >>>> PPAS: snwh/ppa
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:snwh/ppa
sudo apt-get update -y
# >>>> PKGS: moka-icon-theme
sudo apt-get install -y \
	moka-icon-theme
