#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'moka-icon-theme' | grep -q "\[installed\]")
then
   echo "[moka-icon-theme] -> [installed!]";
else
   echo "[moka-icon-theme] -> [NOT installed!]";
   missing=1;
fi
