#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: bat
#		 > Template: apt

printf "bat > %s\n" "$(apt-cache policy bat | grep Candidate | cut -d: -f2 | tr -d /" /")"
