#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: baobab
#		 > Template: apt

printf "baobab > %s\n" "$(apt-cache policy baobab | grep Installed | cut -d: -f2 | tr -d /" /")"
