#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: baobab
#		 > Template: apt

printf "baobab > %s\n" "$(apt-cache policy baobab | grep Installed | cut -d: -f2 | tr -d /" /")"
