#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: baobab
#		 > Template: apt

printf "baobab > %s\n" "$(apt-cache policy baobab | grep Candidate | cut -d: -f2 | tr -d /" /")"
