#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'clamav' | grep -q "\[installed\]")
then
   echo "[clamav] -> [installed!]";
else
   echo "[clamav] -> [NOT installed!]";
   missing=1;
fi


if $(apt list --installed 'clamav-daemon' | grep -q "\[installed\]")
then
   echo "[clamav-daemon] -> [installed!]";
else
   echo "[clamav-daemon] -> [NOT installed!]";
   missing=1;
fi
