#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > autojump
#		 > apt

printf "autojump > %s\n" "$(apt-cache policy autojump | grep Installed | cut -d: -f2 | tr -d /" /")"
