#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > UPSTREAM-VER.SH
#		 > autojump
#		 > apt

printf "autojump > %s\n" "$(apt-cache policy autojump | grep Candidate | cut -d: -f2 | tr -d /" /")"
