#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: opensnitch
#		 > Template: deb

# Variables
INSTALL_DST="${INSTALL_DST:-${HOME}/.local/bin/}"
BASHCOMP_P="${BASHCOMP_P:-${HOME}/.config/bash/bash_completion}"
ZSHCOMP="${ZSHCOMP:-${HOME}/.config/zsh/completions}"
TEMPDIR="$(mktemp -d -t XXXXXXXXXX)"
FMT='\e[0;34m%-6s\e[m\n'
# Commands
DLTMP=$(mktemp -d -t jumpstart-XXXXXXXXXX) \
&& cd "${DLTMP}" \
&& printf "\e[0;34m%-6s\e[m\n" "Downloading to $(realpath .)" \
&& URL=$(curl --silent 'https://api.github.com/repos/evilsocket/opensnitch/releases/latest' | jq '..|.browser_download_url? | select( . != null )' | tr -d '"' | grep --ignore-case 'ui' | grep --ignore-case 'deb' | grep --ignore-case --invert-match 'PIP') \
&& curl -jLO "${URL}" \
&& DLFILE=$(ls . | head -n1) \
&& sudo apt install -y "$(realpath ${DLFILE})"


printf "Issues with Ubuntu 22.04 (fixed in 23.04)\n";
printf "https://github.com/evilsocket/opensnitch/issues/647#issuecomment-1090545284\n";
printf "\tpython3.10 -m pip install --ignore-installed grpcio\n";
