#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'nomacs' | grep -q "\[installed\]")
then
   echo "[nomacs] -> [installed!]";
else
   echo "[nomacs] -> [NOT installed!]";
   missing=1;
fi
