#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: peek
#		 > Template: apt

printf "peek > %s\n" "$(apt-cache policy peek | grep Installed | cut -d: -f2 | tr -d /" /")"
