#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: Flatseal
#		 > Template: flatpak

flatpak install -y flathub com.github.alainm23.planner
