#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: Flatseal
#		 > Template: flatpak

printf "com.github.alainm23.planner > %s\n" "$(flatpak info com.github.alainm23.planner | grep Version | cut -d: -f2 | tr -d /" /")"
