#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: stretchly
#		 > Template: flatpak

printf "net.hovancik.Stretchly > %s\n" "$(flatpak info net.hovancik.Stretchly | grep Version | cut -d: -f2 | tr -d /" /")"
