#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > stretchly
#		 > flatpak

printf "net.hovancik.Stretchly > %s\n" "$(flatpak info net.hovancik.Stretchly | grep Version | cut -d: -f2 | tr -d /" /")"
