#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: stretchly
#		 > Template: flatpak

flatpak uninstall net.hovancik.Stretchly  --delete-data
