git add ./7zip/apt/remove.sh
git add ./anki/apt/remove.sh
git add ./apt-remove.sh
git add ./aptitude/apt/remove.sh
git add ./arandr/apt/remove.sh
git add ./autojump/apt/remove.sh
git add ./baobab/apt/remove.sh
git add ./bat/apt/remove.sh
git add ./blender/apt/remove.sh
git add ./checkinstall/apt/remove.sh
git add ./clamav/apt/remove.sh
git add ./cmake/apt/remove.sh
git add ./cmus/apt/remove.sh
git add ./cookiecutter/apt-broken/remove.sh
git add ./curl/apt/remove.sh
git add ./dconf-editor/apt/remove.sh
git add ./doas/apt/remove.sh
git add ./dos2unix/apt/remove.sh
git add ./dunst/apt/remove.sh
git add ./entr/apt/remove.sh
git add ./exfat/apt/remove.sh
git add ./fd-find/apt/remove.sh
git add ./firewall-gui/apt/remove.sh
git add ./flameshot/apt/remove.sh
git add ./flatpak/apt/remove.sh
git add ./font-awesome/apt/remove.sh
git add ./fzf/apt/remove.sh
git add ./git/apt/remove.sh
git add ./gnome-tweaks/apt/remove.sh
git add ./gparted/apt/remove.sh
git add ./graphviz/apt/remove.sh
git add ./gromit-mpx/apt/remove.sh
git add ./grsync/apt/remove.sh
git add ./httrack/apt/remove.sh
git add ./imagemagick/apt/remove.sh
git add ./jq/apt/remove.sh
git add ./jre/apt/remove.sh
git add ./latex/apt/remove.sh
git add ./lmms/apt/remove.sh
git add ./meld/apt/remove.sh
git add ./moreutils/apt/remove.sh
git add ./mupdf/apt/remove.sh
git add ./mutt/apt/remove.sh
git add ./ncdu/apt/remove.sh
git add ./neofetch/apt/remove.sh
git add ./neovim/apt/remove.sh
git add ./netcat/apt/remove.sh
git add ./nmap/apt/remove.sh
git add ./nomacs/apt/remove.sh
git add ./nvtop/apt/remove.sh
git add ./openvpn/apt/remove.sh
git add ./paraview/apt/remove.sh
git add ./pavucontrol/apt/remove.sh
git add ./pdfchain/apt/remove.sh
git add ./peek/apt/remove.sh
git add ./pinta/apt/remove.sh
git add ./pipe-viewer/apt/remove.sh
git add ./ppa-purge/apt/remove.sh
git add ./pygments/apt/remove.sh
git add ./python3/apt/remove.sh
git add ./redshift/apt/remove.sh
git add ./ripgrep/apt/remove.sh
git add ./rsync/apt/remove.sh
git add ./shutter/apt/remove.sh
git add ./software-properties-common/apt/remove.sh
git add ./source-highlight/apt/remove.sh
git add ./sqlite/apt/remove.sh
git add ./ssh/apt/remove.sh
git add ./suckless-tools/apt/remove.sh
git add ./sxiv/apt/remove.sh
git add ./sysprof/apt/remove.sh
git add ./texstudio/apt/remove.sh
git add ./tmux/apt/remove.sh
git add ./totem/apt/remove.sh
git add ./trash-cli/apt/remove.sh
git add ./tree/apt/remove.sh
git add ./vim/apt/remove.sh
git add ./virtualbox/apt/remove.sh
git add ./vlc/apt/remove.sh
git add ./watchman/apt/remove.sh
git add ./wget/apt/remove.sh
git add ./xclip/apt/remove.sh
git add ./xcwd/apt/remove.sh
git add ./xournalpp/apt/remove.sh
git add ./yadm/apt/remove.sh
git add ./zip/apt/remove.sh
