#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > totem
#		 > apt

printf "gstreamer1.0-libav > %s\n" "$(apt-cache policy gstreamer1.0-libav | grep Installed | cut -d: -f2 | tr -d /" /")"
