#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: Live Captions
#		 > Template: flatpak

flatpak install -y flathub net.sapples.LiveCaptions
