#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: Live Captions
#		 > Template: flatpak

printf "net.sapples.LiveCaptions > %s\n" "$(flatpak info net.sapples.LiveCaptions | grep Version | cut -d: -f2 | tr -d /" /")"
