#!/usr/bin/env sh
# AUTOGENERATED FILE! DO NOT MODIFY

missing=0;

if $(apt list --installed 'suckless-tools' | grep -q "\[installed\]")
then
   echo "[suckless-tools] -> [installed!]";
else
   echo "[suckless-tools] -> [NOT installed!]";
   missing=1;
fi
