#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > INSTALL.SH
#		 > KeePassXC
#		 > apt

sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo apt-get update -y
sudo apt-get install -y keepassxc
