#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: KeePassXC
#		 > Template: apt

# <<<PRE STAGE>>>

printf "There's also a *universe* one that's more outdated\n";
sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo apt-get update -y
sudo apt-get install -y keepassxc
