#!/bin/bash
# <<<PRE STAGE>>>

printf "There's also a *universe* one that's more outdated\n";
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: KeePassXC
#		 > Template: apt

sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo apt-get update -y
sudo apt-get install -y keepassxc
