#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: KeePassXC
#		 > Template: apt

printf "keepassxc > %s\n" "$(apt-cache policy keepassxc | grep Installed | cut -d: -f2 | tr -d /" /")"
