#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > KeePassXC
#		 > apt

printf "keepassxc > %s\n" "$(apt-cache policy keepassxc | grep Installed | cut -d: -f2 | tr -d /" /")"
