#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: KeePassXC
#		 > Template: apt

printf "keepassxc > %s\n" "$(apt-cache policy keepassxc | grep Candidate | cut -d: -f2 | tr -d /" /")"
