#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: install.sh
#		 >     Name: gitkraken
#		 > Template: deb

# Variables

# Commands
DLTMP=$(mktemp -d -t jumpstart-XXXXXXXXXX) \
&& cd "${DLTMP}" \
&& printf "\e[0;34m%-6s\e[m\n" "Downloading to $(realpath .)" \
&& URL=$(echo "https://release.gitkraken.com/linux/gitkraken-amd64.deb") \
&& curl -jLO "${URL}" \
&& DLFILE=$(ls . | head -n1) \
&& sudo apt install -y "$(realpath ${DLFILE})"
