#!/bin/bash

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: mupdf
#		 > Template: apt

printf "mupdf > %s\n" "$(apt-cache policy mupdf | grep Installed | cut -d: -f2 | tr -d /" /")"
