#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: mupdf
#		 > Template: apt

printf "mupdf > %s\n" "$(apt-cache policy mupdf | grep Candidate | cut -d: -f2 | tr -d /" /")"
