name: pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Set up Pre-commit
    runs-on: ubuntu-latest
    env:
      CODE_DIR: ${{ github.workspace }}/${{ github.repository }}
      VENV_DIR: ${{ github.workspace }}/${{ github.repository }}/venv

    steps:
      - name: Blank slate
        run: |
          echo "Clean up ${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"
          rm -rf "${{ github.workspace }}"/*

      - name: Give Access to the repo
        uses: actions/checkout@v2

      - name: Set up python venv
        shell: bash
        run: |
          sudo apt-get install -y git python3 python3.8-venv curl \
          && mkdir -p "${VENV_DIR}" \
          && python3 -m venv "${VENV_DIR}"                    \
          && "${VENV_DIR}/bin/pip" install --upgrade pip setuptools wheel \
          && "${VENV_DIR}/bin/pip" install "${CODE_DIR}" \
          && "${VENV_DIR}/bin/pip" install -r "${CODE_DIR}"/requirements-dev.txt \

      - name: Run pre-commit
        shell: bash
        run: |
          cd "${CODE_DIR}" \
          && "${VENV_DIR}/bin/pre-commit" run -a
