#!/usr/bin/env python3

"""
Only meant to be imported within cog
"""

# stdlib imports
import typing as T

SH_SHEBANG: T.Final[str] = "#!/usr/bin/env sh"

HEADER: T.Final[str] = "<<<AUTOGENERATED FILE - DO NOT MODIFY>>>"


def str2list(long_string: str) -> list[str]:
    long_string = long_string.replace('"', "").replace("'", "").strip()
    if not long_string:
        return []
    return [p.strip() for p in long_string.split(",")]
