#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: tmux
#		 > Template: apt

printf "tmux > %s\n" "$(apt-cache policy tmux | grep Installed | cut -d: -f2 | tr -d /" /")"
