#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: upstream-ver.sh
#		 >     Name: tmux
#		 > Template: apt

printf "tmux > %s\n" "$(apt-cache policy tmux | grep Candidate | cut -d: -f2 | tr -d /" /")"
