#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > INSTALL.SH
#		 > opensnitch
#		 > deb

# Variables
INSTALL_DST="${INSTALL_DST:-${HOME}/.local/bin/}"
BASHCOMP_P="${BASHCOMP_P:-${HOME}/.config/bash/bash_completion}"
ZSHCOMP="${ZSHCOMP:-${HOME}/.config/zsh/completions}"
TEMPDIR="$(mktemp -d -t XXXXXXXXXX)"
FMT='\e[0;34m%-6s\e[m\n'
# Commands
DLTMP=$(mktemp -d -t jumpstart-XXXXXXXXXX) \
    && cd "${DLTMP}" \
    && printf "\e[0;34m%-6s\e[m\n" "Downloading to $(realpath .)" \
    && URL=$(curl --silent 'https://api.github.com/repos/evilsocket/opensnitch/releases/latest' | jq '..|.browser_download_url? | select( . != null )' | tr -d '"' | grep --ignore-case 'amd64' | grep --ignore-case 'deb') \
    && curl -jLO "${URL}" \
    && DLFILE=$(ls . | head -n1) \
    && sudo apt install -y "$(realpath ${DLFILE})"


printf "You might need to enable the service if it has not been enabled automatically\n";
printf "\tsudo systemctl enable opensnitch; sudo systemctl start opensnitch\n";