#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 > LOCAL-VER.SH
#		 > Planner
#		 > flatpak

printf "com.github.alainm23.planner > %s\n" "$(flatpak info com.github.alainm23.planner | grep Version | cut -d: -f2 | tr -d /" /")"
