#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: Planner
#		 > Template: flatpak

printf "com.github.alainm23.planner > %s\n" "$(flatpak info com.github.alainm23.planner | grep Version | cut -d: -f2 | tr -d /" /")"
