#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: remove.sh
#		 >     Name: Planner
#		 > Template: flatpak

flatpak uninstall com.github.alainm23.planner  --delete-data
