#!/usr/bin/env sh
# <<<AUTOGENERATED - DO NOT MODIFY>>>
#		 >     File: local-ver.sh
#		 >     Name: nvtop
#		 > Template: apt

printf "nvtop > %s\n" "$(apt-cache policy nvtop | grep Installed | cut -d: -f2 | tr -d /" /")"
